environment:
  num_clients: 4
  num_selected_clients: 4
  num_malicious_clients: 0
  experiment_name: "cifar10_lenet5"
  use_config_dir: false

server:
  num_rounds: 1
  num_test_batches: 1
  aggregator:
    name: FedAvg
  global_learning_rate: 1.0

client:
  model_name: lenet5_cifar
  model_init_path: "/home/dai/rofl-project-code/models/cifar_lenet5_initialized.txt"
  clip: ~
  quantization:
    type: probabilistic
    bits: 8
    frac: 7 
  benign_training:
    num_epochs: 0
    batch_size: 64
    optimizer: SGD
    learning_rate: 0.01

crypto:
  enc_type: l2 #l2, Range, Plain
  value_range: 16
  n_partition: 1
  l2_value_range: 16
  check_percentage: 1.0 # 0.0-1.0 for Range i.e., round(num_rangeproofs * check_percentage)
  fp_bits: 16
  fp_frac: 7

dataset:
  augment_data: false
  dataset: cifar10
  data_distribution: IID

job:
  minutes: 1440 # Max. minutes to run. Leonhard has 240 and 1440 queues
  cpu_cores: 20
  cpu_mem_per_core: 4096
  use_gpu: 1
  gpu_memory_min: 10240